name: Workflow Events
on: [workflow_dispatch,push,pull_request]
jobs:
  echo_job:
    runs-on: ubuntu-latest
    steps:
      - name: echo
      - run: echo "I've been triggered by ${{ github.event_name }} event"
